### ISSUE TITLE
Minification Error

### ISSUE THREAD

**Issue by devashreeganesha108gmailcom** [shukerullah/react-geocode#11]
Hi there...

I see that a couple of people have posted their issues with the problems with minification. I wonder whether you used ES6 or ES5. After doing some googling I found the problem may be due to the ES6 code not getting converted to ES5 code for minification. I am also stuck with deploying a web application I built using heroku or AWS.

Would be great if you could post a resolution for this problem soon..
Any help would be greatly appreciated..

Thanks..

**Comment by cworf** [comment]
I am also having this issue. seems like its been a problem for a month now, any chance of getting it fixed?

**Comment by devashreeganesha108gmailcom** [comment]
Well I ended up using a different library for doing the geocoding.

**Comment by cworf** [comment]
I fixed the issue on my own by manually converting this packages index.js file to es5... simple enough, here's the code for anyone who has this problem, confirmed working.
 
```javascript
require("babel-core/register");
require("babel-polyfill");

"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var handleUrl = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(url) {
    var response, json;
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.next = 2;
            return fetch(url).catch(function (error) {
              return Promise.reject(new Error("Error fetching data"));
            });

          case 2:
            response = _context.sent;
            _context.next = 5;
            return response.json().catch(function () {
              log("Error parsing server response");
              return Promise.reject(new Error("Error parsing server response"));
            });

          case 5:
            json = _context.sent;

            if (!(json.status === "OK")) {
              _context.next = 9;
              break;
            }

            log(json);
            return _context.abrupt("return", json);

          case 9:
            log("Server returned status code " + json.status, true);
            return _context.abrupt("return", Promise.reject(new Error("Server returned status code " + json.status)));

          case 11:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function handleUrl(_x) {
    return _ref.apply(this, arguments);
  };
}();

function _asyncToGenerator(fn) {
  return function () {
    var gen = fn.apply(this, arguments);return new Promise(function (resolve, reject) {
      function step(key, arg) {
        try {
          var info = gen[key](arg);var value = info.value;
        } catch (error) {
          reject(error);return;
        }if (info.done) {
          resolve(value);
        } else {
          return Promise.resolve(value).then(function (value) {
            step("next", value);
          }, function (err) {
            step("throw", err);
          });
        }
      }return step("next");
    });
  };
}

/**
 * React Geocode Module
 *
 * @package react-geocode
 * @author  Pir Shukarulalh Shah <shuker_rashdi@hotmail.com> (http://www.shukarullah.com)
 */

var DEBUG = false;
var API_KEY = null;
var GOOGLE_API = "https://maps.google.com/maps/api/geocode/json";

function log(message) {
  var warn = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : false;

  if (DEBUG) {
    if (warn) {
      console.warn(message);
    } else {
      console.log(message);
    }
  }
}

exports.default = {
  /**
   *
   *
   * @param {string} apiKey
   */
  setApiKey: function setApiKey(apiKey) {
    API_KEY = apiKey;
  },


  /**
   *
   *
   * @param {boolean} [flag=true]
   */
  enableDebug: function enableDebug() {
    var flag = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : true;

    DEBUG = flag;
  },


  /**
   *
   *
   * @param {string} lat
   * @param {string} lng
   * @param {string} [apiKey]
   * @returns {Promise}
   */
  fromLatLng: function fromLatLng(lat, lng, apiKey) {
    return _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee2() {
      var latLng, url;
      return regeneratorRuntime.wrap(function _callee2$(_context2) {
        while (1) {
          switch (_context2.prev = _context2.next) {
            case 0:
              if (!(!lat || !lng)) {
                _context2.next = 3;
                break;
              }

              log("Provided coordinates are invalid", true);
              return _context2.abrupt("return", Promise.reject(new Error("Provided coordinates are invalid")));

            case 3:
              latLng = lat + "," + lng;
              url = GOOGLE_API + "?latlng=" + encodeURI(latLng);


              if (apiKey || API_KEY) {
                API_KEY = apiKey || API_KEY;
                url += "&key=" + API_KEY;
              }

              return _context2.abrupt("return", handleUrl(url));

            case 7:
            case "end":
              return _context2.stop();
          }
        }
      }, _callee2, this);
    }))();
  },


  /**
   *
   *
   * @param {string} address
   * @param {string} [apiKey]
   * @returns {Promise}
   */
  fromAddress: function fromAddress(address, apiKey) {
    return _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee3() {
      var url;
      return regeneratorRuntime.wrap(function _callee3$(_context3) {
        while (1) {
          switch (_context3.prev = _context3.next) {
            case 0:
              if (address) {
                _context3.next = 3;
                break;
              }

              log("Provided address is invalid", true);
              return _context3.abrupt("return", Promise.reject(new Error("Provided address is invalid")));

            case 3:
              url = GOOGLE_API + "?address=" + encodeURI(address);


              if (apiKey || API_KEY) {
                API_KEY = apiKey || API_KEY;
                url += "&key=" + API_KEY;
              }

              return _context3.abrupt("return", handleUrl(url));

            case 6:
            case "end":
              return _context3.stop();
          }
        }
      }, _callee3, this);
    }))();
  }
};

```

**Comment by Louventia** [comment]
Hello! I also having this issue and I saw your post! I tried copying the code. However, I am still having the same issue. I have tried to `sudo npm run build` Please advise! >.<

<img width="490" alt="screen shot 2018-05-14 at 3 03 32 pm" src="https://user-images.githubusercontent.com/38120930/39982777-036bb1a2-5788-11e8-87ea-d04b39726ae0.png">

**Comment by cworf** [comment]
Devashreeganesh, can you advise on which package you used instead? It looks like this one is no longer being supported anyways.

**Comment by shukerullah** [comment]
I have minified can you please update to v0.0.8? Thank you for your patience and continued support.

**Comment by LopezChris616** [comment]
> I have minified can you please update to v0.0.8? Thank you for your patience and continued support.

I'm using v0.0.9 and I'm still getting an error that it isn't minifying correctly. I'm using Create-React-App's `"react-scripts build"` command and getting the following error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/react-geocode/lib/index.js:2
```

Any insights @shukerullah ?

**Comment by shukerullah** [comment]
I have updated this lib to v0.1.2 and tested with create-react-app's `"react-scripts build"` command. Please update to latest version.
